# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Add make
          command: |
            apk update
            apk add make=4.2.1-r2
      - run:
          name: Build image
          command: make build/image

workflows:
  app:
    jobs:
      - build
